[project]
name = "portal-stillalive-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "playsound==1.2.2",
    "pyobjc>=11.1",
]
